(set vim.o.iskeyword (.. vim.o.iskeyword  ",-")) 
(set vim.o.tabstop 4) 
(set vim.o.timeoutlen 300) 
(set vim.o.expandtab true) 
(set vim.o.softtabstop 2) 
(set vim.o.smartindent true) 
(set vim.o.shiftwidth 2)
(set vim.o.autoindent true) 
(set vim.o.smarttab true) 

(set vim.o.undofile true) 
(set vim.o.undodir "/tmp/nvim-undos") 
